-- AlterTable
ALTER TABLE `estudiante` MODIFY `fecha_nac` DATETIME(3) NULL,
    MODIFY `email` VARCHAR(191) NULL,
    MODIFY `telefono` VARCHAR(191) NULL,
    MODIFY `direccion` VARCHAR(191) NULL,
    MODIFY `ciudad` VARCHAR(191) NULL,
    MODIFY `estado` VARCHAR(191) NULL,
    MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) NULL;
